services:
  ros2:
    environment:
      DISPLAY: ${RMPD_XQUARTZ_DISPLAY:-host.docker.internal:0}
      QT_X11_NO_MITSHM: "1"
      QT_QPA_PLATFORM: ${RMPD_QT_QPA_PLATFORM:-xcb}
      QT_XCB_GL_INTEGRATION: ${RMPD_QT_XCB_GL_INTEGRATION:-none}
      LIBGL_ALWAYS_SOFTWARE: ${RMPD_LIBGL_ALWAYS_SOFTWARE:-1}
