#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export RMPD_WEBOTS_WORLD="$REPO_DIR/webots/worlds/office/office.wbt"
export RMPD_AMCL_MAP_NAME="office"
export RMPD_AMCL_INITIAL_POSE_X="-4.35"
export RMPD_AMCL_INITIAL_POSE_Y="-5.35"
export RMPD_AMCL_INITIAL_POSE_YAW="0.004641574238792719"
export RMPD_AMCL_INITIAL_POSE_USE_ODOM="${RMPD_AMCL_INITIAL_POSE_USE_ODOM:-false}"
export RMPD_QUICK_TEST_RVIZ_CONFIG="amcl.rviz"
export RMPD_START_CHECKPOINT_PATROL="${RMPD_START_CHECKPOINT_PATROL:-false}"
export RMPD_START_LIVE_MAPPING="${RMPD_START_LIVE_MAPPING:-true}"
export RMPD_LIVE_MAP_WIDTH_M="${RMPD_LIVE_MAP_WIDTH_M:-20.0}"
export RMPD_LIVE_MAP_HEIGHT_M="${RMPD_LIVE_MAP_HEIGHT_M:-20.0}"
export WEBOTS_DRIVE_SPEED="${WEBOTS_DRIVE_SPEED:-2.4}"
export WEBOTS_TURN_SPEED="${WEBOTS_TURN_SPEED:-1.6}"

exec bash "$REPO_DIR/scripts/quick_test.sh"
