#!/usr/bin/env bash
set -euo pipefail
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORLD_DIR="$REPO_DIR/webots/worlds/twoRoute"
SOURCE_WORLD="$WORLD_DIR/two_route.wbt"
SANDBOX_WORLD="$WORLD_DIR/sandbox.wbt"

cleanup() {
  rm -f "$SANDBOX_WORLD"
}

trap cleanup EXIT

cp "$SOURCE_WORLD" "$SANDBOX_WORLD"
export RMPD_WEBOTS_WORLD="$SANDBOX_WORLD"
export RMPD_AMCL_MAP_NAME="two_route"
export RMPD_AMCL_INITIAL_POSE_X="-4.5"
export RMPD_AMCL_INITIAL_POSE_Y="1.0"
export RMPD_AMCL_INITIAL_POSE_YAW="0.0"
export RMPD_AMCL_INITIAL_POSE_USE_ODOM="${RMPD_AMCL_INITIAL_POSE_USE_ODOM:-true}"
export RMPD_QUICK_TEST_RVIZ="${RMPD_QUICK_TEST_RVIZ:-auto}"
export RMPD_QUICK_TEST_RVIZ_CONFIG="amcl.rviz"
export RMPD_START_CHECKPOINT_PATROL="${RMPD_START_CHECKPOINT_PATROL:-true}"
export RMPD_START_NAVIGATION_DIAGNOSTICS="${RMPD_START_NAVIGATION_DIAGNOSTICS:-true}"
export RMPD_START_LIVE_MAPPING="${RMPD_START_LIVE_MAPPING:-true}"
export WEBOTS_CHECKPOINT_CENTER_RADIUS="${WEBOTS_CHECKPOINT_CENTER_RADIUS:-0.20}"
export RMPD_LIVE_MAP_WIDTH_M="${RMPD_LIVE_MAP_WIDTH_M:-14.0}"
export RMPD_LIVE_MAP_HEIGHT_M="${RMPD_LIVE_MAP_HEIGHT_M:-6.0}"
export RMPD_LIVE_MAP_ORIGIN_X="${RMPD_LIVE_MAP_ORIGIN_X:--6.5}"
export RMPD_LIVE_MAP_ORIGIN_Y="${RMPD_LIVE_MAP_ORIGIN_Y:--3.0}"
bash "$REPO_DIR/scripts/quick_test.sh"
